dougdellolio/coinbasepro-csharp

GDAXClient.Specs/GDAXClient.Specs.csproj
GDAXClient.Specs/Services/Products/ProductsServiceSpecs.cs
GDAXClient.Specs/packages.config
GDAXClient/GDAXClient.csproj
GDAXClient/Services/Products/Models/Candle.cs
GDAXClient/Services/Products/Models/CandleGranularity.cs
GDAXClient/Services/Products/ProductsService.cs
GDAXClient/Utilities/CandleConverter.cs
README.md

See #43 
Serialize instead to IList<Candle>

Output of GetHistoricRatesAsync not consistent

---

GDAXSharp.Specs/Services/Accounts/AccountsServiceSpecs.cs
GDAXSharp.Specs/Services/CoinbaseAccounts/CoinbaseAccountsServiceSpecs.cs
GDAXSharp.Specs/Services/Currencies/CurrenciesServiceSpecs.cs
GDAXSharp.Specs/Services/Deposits/DepositsServiceSpecs.cs
GDAXSharp.Specs/Services/Fills/FillsServiceSpecs.cs
GDAXSharp.Specs/Services/Fundings/FundingsServiceSpecs.cs
GDAXSharp.Specs/Services/Orders/OrdersServiceSpecs.cs
GDAXSharp.Specs/Services/Payments/PaymentsServiceSpecs.cs
GDAXSharp.Specs/Services/Products/ProductsServiceSpecs.cs
GDAXSharp.Specs/Services/Reports/ReportsServiceSpecs.cs
GDAXSharp.Specs/Services/Withdrawals/WithdrawalsServiceSpecs.cs
GDAXSharp/GDAXClient.cs
GDAXSharp/HttpClient/HttpClient.cs
GDAXSharp/HttpClient/IHttpClient.cs
GDAXSharp/Services/AbstractService.cs
README.md

[Feature] Allow consumer to pass in an IHttpClient in [#85]

---

GDAXSharp.Specs/Services/HttpRequest/HttpRequestMessageServiceSpecs.cs
GDAXSharp/GDAXClient.cs
GDAXSharp/Network/HttpRequest/HttpRequestMessageService.cs
GDAXSharp/Network/HttpRequest/IHttpRequestMessageService.cs
GDAXSharp/Services/AbstractService.cs
GDAXSharp/Services/Accounts/AccountsService.cs
GDAXSharp/Services/CoinbaseAccounts/CoinbaseAccountsService.cs
GDAXSharp/Services/Currencies/CurrenciesService.cs
GDAXSharp/Services/Deposits/DepositsService.cs
GDAXSharp/Services/Fills/FillsService.cs
GDAXSharp/Services/Fundings/FundingsService.cs
GDAXSharp/Services/Orders/OrdersService.cs
GDAXSharp/Services/Payments/PaymentsService.cs
GDAXSharp/Services/Products/ProductsService.cs
GDAXSharp/Services/Reports/ReportsService.cs
GDAXSharp/Services/UserAccount/UserAccountService.cs
GDAXSharp/Services/Withdrawals/WithdrawalsService.cs

Authenticator was getting passed into the Services, only to be passed into HttpRequestMessageService on each call for actual usage.
Change to store it in HttpRequestMessageService.

[Refactor] Use of Authenticator 

---

GDAXSharp/Network/HttpClient/HttpClient.cs
GDAXSharp/Services/Products/ProductsService.cs

See #103 
Also #49 needs a tweak - it gives stack overflow as both classes are called HttpClient

[Bug] Fix HttpClient and GetHistoricRates no candle returned

---

GDAXSharp.Specs/Services/HttpRequest/HttpRequestMessageServiceSpecs.cs
GDAXSharp.Specs/WebSocket/WebSocketSpecs.cs
GDAXSharp/GDAXClient.cs
GDAXSharp/Network/HttpRequest/HttpRequestMessageService.cs
GDAXSharp/WebSocket/WebSocket.cs
GDAXSharp/WebSocket/WebSocketFeed.cs
README.md

[Feature] Add ability to connect to Websocket without authentication

---

GDAXSharp.sln
GDAXSharp/GDAXClient.cs
GDAXSharp/GDAXSharp.csproj
GDAXSharp/Services/AbstractService.cs
GDAXSharp/Shared/Utilities/JsonConfig.cs
GDAXSharp/WebSocket/Types/ResponseType.cs
GDAXSharp/WebSocket/WebSocket.cs
README.md

Have gone for a minimum logging footprint.
I can update for any comments / improvements etc.

[Feature] Logging via Serilog (#105)

---

CoinbasePro.Specs/WebSocket/WebSocketSpecs.cs
CoinbasePro/WebSocket/WebSocket.cs

Fix GetChannels to return only the channels specified in channelTypes. Current codes returns all channels defined in CoinbasePro.WebSocket.Types.ChannelType.

GetChannels Subscription Fix

---

CoinbasePro.Specs/WebSocket/WebSocketSpecs.cs
CoinbasePro/WebSocket/WebSocket.cs

Add functionality requested in [Feature] Ability to add and remove subscriptions on the fly https://github.com/dougdellolio/coinbasepro-csharp/issues/129

Allow Dynamic Channel Subscriptions

---

CoinbasePro/Shared/Types/Currency.cs
CoinbasePro/Shared/Types/ProductType.cs

https://blog.coinbase.com/zrx-is-launching-on-coinbase-pro-29ae77eadc42

[Feature] Add support for ZRX

---

CoinbasePro.Specs/JsonFixtures/Services/Accounts/AllAccountsResponseFixture.cs
CoinbasePro.Specs/JsonFixtures/Services/Currencies/CurrenciesResponseFixture.cs
CoinbasePro.Specs/JsonFixtures/Services/Products/ProductsResponseFixture.cs
CoinbasePro.Specs/Services/Accounts/AccountsServiceSpecs.cs
CoinbasePro.Specs/Services/Currencies/CurrenciesServiceSpecs.cs
CoinbasePro.Specs/Services/Orders/OrdersServiceSpecs.cs
CoinbasePro.Specs/Services/Products/ProductsServiceSpecs.cs
CoinbasePro/Services/Accounts/Models/Account.cs
CoinbasePro/Services/Accounts/Models/AccountHistory.cs
CoinbasePro/Services/CoinbaseAccounts/Models/CoinbaseAccount.cs
CoinbasePro/Services/Currencies/Models/Currency.cs
CoinbasePro/Services/Deposits/Models/Responses/DepositResponse.cs
CoinbasePro/Services/Fills/Models/Responses/FillResponse.cs
CoinbasePro/Services/Fundings/Models/Funding.cs
CoinbasePro/Services/Orders/Models/Order.cs
CoinbasePro/Services/Orders/Models/Responses/OrderResponse.cs
CoinbasePro/Services/Payments/Models/PaymentMethod.cs
CoinbasePro/Services/Products/Models/Product.cs
CoinbasePro/Services/Reports/Models/Report.cs
CoinbasePro/Services/UserAccount/Models/TrailingVolume.cs
CoinbasePro/Services/Withdrawals/Models/Coinbase.cs
CoinbasePro/Services/Withdrawals/Models/Crypto.cs
CoinbasePro/Services/Withdrawals/Models/Responses/CoinbaseResponse.cs
CoinbasePro/Services/Withdrawals/Models/Responses/WithdrawalResponse.cs
CoinbasePro/Services/Withdrawals/Models/Withdrawal.cs
CoinbasePro/Shared/StringEnumWithDefaultConverter.cs
CoinbasePro/Shared/Types/Currency.cs
CoinbasePro/Shared/Types/ProductType.cs
CoinbasePro/Shared/Utilities/JsonConfig.cs

This PR aims to handle the case when Coinbase adds new product types and currencies. Currently an error is thrown because it can't properly deserialize the types.

[Feature] Add unknown types to handle new Product Types and Currencies

---

CoinbasePro.Specs/WebSocket/WebSocketSpecs.cs
CoinbasePro/WebSocket/IWebSocket.cs
CoinbasePro/WebSocket/IWebSocketFeed.cs
CoinbasePro/WebSocket/WebSocket.cs
CoinbasePro/WebSocket/WebSocketFeed.cs

Set the auto send ping interval to prevent websocket from closing if idle:
```csharp
var client = new CoinbaseProClient();
var websocket = client.WebSocket;
websocket.Start(productTypes, channels);
websocket.SetAutoSendPingInterval(30); //set after .Start() is called
```

[Feature] Ability to set auto send ping interval on Websocket

---

CoinbasePro.Specs/JsonFixtures/Services/StablecoinConversions/StablecoinConversionsResponseFixture.cs
CoinbasePro.Specs/Services/StablecoinConversions/StablecoinConversionsServiceSpecs.cs
CoinbasePro.Specs/app.config
CoinbasePro/CoinbaseProClient.cs
CoinbasePro/Exceptions/CoinbaseProHttpException.cs
CoinbasePro/Services/StablecoinConversions/Models/StablecoinConversionResponse.cs
CoinbasePro/Services/StablecoinConversions/StablecoinConversion.cs
CoinbasePro/Services/StablecoinConversions/StablecoinConversionsService.cs
README.md

New stablecoin conversions API: https://docs.pro.coinbase.com/#stablecoin-conversions

[Feature] Add Stablecoin Conversions service

---

CoinbasePro.Specs/JsonFixtures/Services/Accounts/AccountsHistoryResponseFixture.cs
CoinbasePro.Specs/Services/Accounts/AccountsServiceSpecs.cs
CoinbasePro/Services/Accounts/Models/AccountHistory.cs
CoinbasePro/Services/Accounts/Types/AccountEntryType.cs

fixes #180 
This adds new conversion account entry type and also prevents future new types from causing an exception to be thrown.

[Feature] Add conversion account entry type

---

CoinbasePro.Specs/Services/Orders/OrdersServiceSpecs.cs
CoinbasePro/CoinbaseProClient.cs
CoinbasePro/Network/Authentication/Authenticator.cs
CoinbasePro/Network/Authentication/IAuthenticator.cs
CoinbasePro/Services/Orders/OrdersService.cs
README.md

fixes https://github.com/dougdellolio/coinbasepro-csharp/issues/156

[Feature] Ability to define multiple statuses in get order request

---

CoinbasePro.Specs/JsonFixtures/Websocket/WebSocketTypeResponseFixture.cs
CoinbasePro.Specs/WebSocket/WebSocketSpecs.cs
CoinbasePro/WebSocket/Models/Response/Received.cs

[Bug] Handle empty client_oid in Websocket received calls

---

CoinbasePro/Shared/ApiUris.cs

Hi there,
Submitting this really small PR that alters the Websocket URI to work in sandbox mode.
Keep up the good work 👍

[Bug] Fix Websocket URI for sandbox

---

CoinbasePro/Services/Products/ProductsService.cs

Fixes a CoinbaseProHttpException being thrown due to batch requests.
The REST API has a public request limit of 3 per second, as seen [here](https://docs.pro.coinbase.com/#rate-limits)

[Bug]Add throttling

---

CoinbasePro.Specs/JsonFixtures/Services/Orders/OrderRequestFixture.cs
CoinbasePro.Specs/JsonFixtures/Services/Orders/OrderResponseFixture.cs
CoinbasePro.Specs/Services/Orders/OrdersServiceSpecs.cs
CoinbasePro/Services/Orders/IOrdersService.cs
CoinbasePro/Services/Orders/OrdersService.cs
README.md

https://github.com/dougdellolio/coinbasepro-csharp/issues/223

[Fix] OrdersService - Placing Stop Order

---

CoinbasePro/Shared/Types/Currency.cs
CoinbasePro/Shared/Types/ProductType.cs

Add UMA Currency and the UmaUsd and UmaBtc Product Types for UMA trading support.

[Feature] Add currency/product type for UMA trading support.

---

CoinbasePro/Shared/Types/Currency.cs
CoinbasePro/Shared/Types/ProductType.cs

Also added DAI-USD product type.

[Feature] Add currency and trading support for CGLD and WBTC.

---

CoinbasePro/WebSocket/Models/Response/Match.cs

I have updated this model per the the latest spec.
See additional details [here](https://github.com/dougdellolio/coinbasepro-csharp/issues/198#issuecomment-774482786).

Update Match model

---

CoinbasePro/ICoinbaseProClient.cs

- exposed IProfileService and ILimitsService from ICoinbaseProClient

Expose missing interfaces
